export interface Localidad {
  ciudad: string
  provincia: string
}

export const LOCALIDADES: Localidad[] = [
  { ciudad: '28 de Julio', provincia: 'Chubut' },
  { ciudad: 'Camarones', provincia: 'Chubut' },
  { ciudad: 'Cholila', provincia: 'Chubut' },
  { ciudad: 'Comodoro Rivadavia', provincia: 'Chubut' },
  { ciudad: 'Corcovado', provincia: 'Chubut' },
  { ciudad: 'Cushamen', provincia: 'Chubut' },
  { ciudad: 'Dolavon', provincia: 'Chubut' },
  { ciudad: 'El Hoyo', provincia: 'Chubut' },
  { ciudad: 'El Maitén', provincia: 'Chubut' },
  { ciudad: 'Epuyén', provincia: 'Chubut' },
  { ciudad: 'Esquel', provincia: 'Chubut' },
  { ciudad: 'Gaiman', provincia: 'Chubut' },
  { ciudad: 'Gan Gan', provincia: 'Chubut' },
  { ciudad: 'Gastre', provincia: 'Chubut' },
  { ciudad: 'Gobernador Costa', provincia: 'Chubut' },
  { ciudad: 'Gualjaina', provincia: 'Chubut' },
  { ciudad: 'José de San Martín', provincia: 'Chubut' },
  { ciudad: 'Lago Puelo', provincia: 'Chubut' },
  { ciudad: 'Las Plumas', provincia: 'Chubut' },
  { ciudad: 'Paso de Indios', provincia: 'Chubut' },
  { ciudad: 'Paso del Sapo', provincia: 'Chubut' },
  { ciudad: 'Puerto Madryn', provincia: 'Chubut' },
  { ciudad: 'Puerto Pirámides', provincia: 'Chubut' },
  { ciudad: 'Rada Tilly', provincia: 'Chubut' },
  { ciudad: 'Rawson', provincia: 'Chubut' },
  { ciudad: 'Río Mayo', provincia: 'Chubut' },
  { ciudad: 'Río Pico', provincia: 'Chubut' },
  { ciudad: 'Río Senguer', provincia: 'Chubut' },
  { ciudad: 'Sarmiento', provincia: 'Chubut' },
  { ciudad: 'Tecka', provincia: 'Chubut' },
  { ciudad: 'Telsen', provincia: 'Chubut' },
  { ciudad: 'Trelew', provincia: 'Chubut' },
  { ciudad: 'Trevelin', provincia: 'Chubut' },
  { ciudad: 'Aluminé', provincia: 'Neuquén' },
  { ciudad: 'Andacollo', provincia: 'Neuquén' },
  { ciudad: 'Añelo', provincia: 'Neuquén' },
  { ciudad: 'Bajada del Agrio', provincia: 'Neuquén' },
  { ciudad: 'Barrancas', provincia: 'Neuquén' },
  { ciudad: 'Buta Ranquil', provincia: 'Neuquén' },
  { ciudad: 'Caviahue-Copahue', provincia: 'Neuquén' },
  { ciudad: 'Centenario', provincia: 'Neuquén' },
  { ciudad: 'Chorriaca', provincia: 'Neuquén' },
  { ciudad: 'Chos Malal', provincia: 'Neuquén' },
  { ciudad: 'Cutral Co', provincia: 'Neuquén' },
  { ciudad: 'El Cholar', provincia: 'Neuquén' },
  { ciudad: 'El Huecú', provincia: 'Neuquén' },
  { ciudad: 'Huinganco', provincia: 'Neuquén' },
  { ciudad: 'Junín de los Andes', provincia: 'Neuquén' },
  { ciudad: 'Las Coloradas', provincia: 'Neuquén' },
  { ciudad: 'Las Lajas', provincia: 'Neuquén' },
  { ciudad: 'Las Ovejas', provincia: 'Neuquén' },
  { ciudad: 'Loncopué', provincia: 'Neuquén' },
  { ciudad: 'Los Catutos', provincia: 'Neuquén' },
  { ciudad: 'Los Miches', provincia: 'Neuquén' },
  { ciudad: 'Manzano Amargo', provincia: 'Neuquén' },
  { ciudad: 'Mariano Moreno', provincia: 'Neuquén' },
  { ciudad: 'Neuquén', provincia: 'Neuquén' },
  { ciudad: 'Picún Leufú', provincia: 'Neuquén' },
  { ciudad: 'Piedra del Águila', provincia: 'Neuquén' },
  { ciudad: 'Plaza Huincul', provincia: 'Neuquén' },
  { ciudad: 'Plottier', provincia: 'Neuquén' },
  { ciudad: 'Rincón de los Sauces', provincia: 'Neuquén' },
  { ciudad: 'San Martín de los Andes', provincia: 'Neuquén' },
  { ciudad: 'San Patricio del Chañar', provincia: 'Neuquén' },
  { ciudad: 'Senillosa', provincia: 'Neuquén' },
  { ciudad: 'Taquimilán', provincia: 'Neuquén' },
  { ciudad: 'Tricao Malal', provincia: 'Neuquén' },
  { ciudad: 'Villa Curi Leuvú', provincia: 'Neuquén' },
  { ciudad: 'Villa El Chocón', provincia: 'Neuquén' },
  { ciudad: 'Villa La Angostura', provincia: 'Neuquén' },
  { ciudad: 'Villa Pehuenia', provincia: 'Neuquén' },
  { ciudad: 'Villa Traful', provincia: 'Neuquén' },
  { ciudad: 'Vista Alegre', provincia: 'Neuquén' },
  { ciudad: 'Zapala', provincia: 'Neuquén' },
  { ciudad: 'Allen', provincia: 'Río Negro' },
  { ciudad: 'Campo Grande', provincia: 'Río Negro' },
  { ciudad: 'Catriel', provincia: 'Río Negro' },
  { ciudad: 'Cervantes', provincia: 'Río Negro' },
  { ciudad: 'Chichinales', provincia: 'Río Negro' },
  { ciudad: 'Chimpay', provincia: 'Río Negro' },
  { ciudad: 'Choele Choel', provincia: 'Río Negro' },
  { ciudad: 'Cinco Saltos', provincia: 'Río Negro' },
  { ciudad: 'Cipolletti', provincia: 'Río Negro' },
  { ciudad: 'Comallo', provincia: 'Río Negro' },
  { ciudad: 'Contralmirante Cordero', provincia: 'Río Negro' },
  { ciudad: 'Coronel Belisle', provincia: 'Río Negro' },
  { ciudad: 'Darwin', provincia: 'Río Negro' },
  { ciudad: 'Dina Huapi', provincia: 'Río Negro' },
  { ciudad: 'El Bolsón', provincia: 'Río Negro' },
  { ciudad: 'El Cuy', provincia: 'Río Negro' },
  { ciudad: 'El Manso', provincia: 'Río Negro' },
  { ciudad: 'Fuerte San Javier', provincia: 'Río Negro' },
  { ciudad: 'General Conesa', provincia: 'Río Negro' },
  { ciudad: 'General Enrique Godoy', provincia: 'Río Negro' },
  { ciudad: 'General Fernández Oro', provincia: 'Río Negro' },
  { ciudad: 'General Roca', provincia: 'Río Negro' },
  { ciudad: 'Guardia Mitre', provincia: 'Río Negro' },
  { ciudad: 'Ingeniero Huergo', provincia: 'Río Negro' },
  { ciudad: 'Ingeniero Jacobacci', provincia: 'Río Negro' },
  { ciudad: 'Lamarque', provincia: 'Río Negro' },
  { ciudad: 'Los Menucos', provincia: 'Río Negro' },
  { ciudad: 'Luis Beltrán', provincia: 'Río Negro' },
  { ciudad: 'Mainqué', provincia: 'Río Negro' },
  { ciudad: 'Maquinchao', provincia: 'Río Negro' },
  { ciudad: 'Ministro Ramos Mexía', provincia: 'Río Negro' },
  { ciudad: 'Ñorquinco', provincia: 'Río Negro' },
  { ciudad: 'Pilcaniyeu', provincia: 'Río Negro' },
  { ciudad: 'Pomona', provincia: 'Río Negro' },
  { ciudad: 'Río Colorado', provincia: 'Río Negro' },
  { ciudad: 'San Antonio Oeste', provincia: 'Río Negro' },
  { ciudad: 'San Carlos de Bariloche', provincia: 'Río Negro' },
  { ciudad: 'Sierra Colorada', provincia: 'Río Negro' },
  { ciudad: 'Sierra Grande', provincia: 'Río Negro' },
  { ciudad: 'Valcheta', provincia: 'Río Negro' },
  { ciudad: 'Valle Azul', provincia: 'Río Negro' },
  { ciudad: 'Viedma', provincia: 'Río Negro' },
  { ciudad: 'Villa Regina', provincia: 'Río Negro' },
  { ciudad: '28 de Noviembre', provincia: 'Santa Cruz' },
  { ciudad: 'Caleta Olivia', provincia: 'Santa Cruz' },
  { ciudad: 'Cañadón Seco', provincia: 'Santa Cruz' },
  { ciudad: 'Comandante Piedra Buena', provincia: 'Santa Cruz' },
  { ciudad: 'El Calafate', provincia: 'Santa Cruz' },
  { ciudad: 'El Chaltén', provincia: 'Santa Cruz' },
  { ciudad: 'Gobernador Gregores', provincia: 'Santa Cruz' },
  { ciudad: 'Jaramillo / Fitz Roy', provincia: 'Santa Cruz' },
  { ciudad: 'Lago Posadas', provincia: 'Santa Cruz' },
  { ciudad: 'Las Heras', provincia: 'Santa Cruz' },
  { ciudad: 'Los Antiguos', provincia: 'Santa Cruz' },
  { ciudad: 'Perito Moreno', provincia: 'Santa Cruz' },
  { ciudad: 'Pico Truncado', provincia: 'Santa Cruz' },
  { ciudad: 'Puerto Deseado', provincia: 'Santa Cruz' },
  { ciudad: 'Puerto San Julián', provincia: 'Santa Cruz' },
  { ciudad: 'Puerto Santa Cruz', provincia: 'Santa Cruz' },
  { ciudad: 'Río Gallegos', provincia: 'Santa Cruz' },
  { ciudad: 'Río Turbio', provincia: 'Santa Cruz' },
  { ciudad: 'Río Grande', provincia: 'Tierra del Fuego' },
  { ciudad: 'Tolhuin', provincia: 'Tierra del Fuego' },
  { ciudad: 'Ushuaia', provincia: 'Tierra del Fuego' },
]

export const PROVINCIAS = Array.from(new Set(LOCALIDADES.map(l => l.provincia))).sort()

export function ciudadesDeProvincia(provincia: string): string[] {
  return LOCALIDADES.filter(l => l.provincia === provincia).map(l => l.ciudad)
}
